
name: Build and test the Docker image

on: [pull_request, push]

jobs:
  build:
    name: Build and test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Specify here the list of images to use for the machine
        os: [ubuntu-22.04]
    steps:
      - name: Checkout the project
        uses: actions/checkout@v2
      - name: Build the Docker image
        shell: bash
        run: make build-docker
      - name: Run tests
        shell: bash
        run: make test-docker
      - name: Synthesisze SoC
        shell: bash
        run: |
          make -C sw/uart_tx
          ./docker_run.py --cmd 'PROJ_NAME=uart_tx ; poetry run ./mtkcpu/cli/top.py build -e sw/$PROJ_NAME/build/$PROJ_NAME.elf'