
name: Build and test the Docker image

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    name: Build and test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # Specify here the list of images to use for the machine
        os: [ubuntu-22.04]
    steps:
      - name: Checkout the project
        uses: actions/checkout@v2
      - name: Build the Docker image
        shell: bash
        run: make build-docker
      - name: SIMULATE UART
        shell: bash
        run: |
          ./docker_run.py --cmd 'poetry run mtkcpu/cli/top.py gen_linker_script'
          ./docker_run.py --cmd 'make -B -C sw/uart_tx'
          : # TODO - the confusing reason why we copy bitstream to /toolchain/sw is that we need to somehow pass it from docker guest to host (github action artifact), and 'docker_run.py' only mounts 'sw' directory.
          timeout 20 ./docker_run.py --cmd 'poetry run ./mtkcpu/cli/top.py sim -e sw/uart_tx/build/uart_tx.elf' || true
